### ISSUE TITLE
custom hanami startup possible?

### ISSUE THREAD

**Issue by breedlovedesign** [angeloashmore/lotus-rethinkdb#4]
`hanami new foo` defaults to sqlite

is there any way to enable something like

`hanami new foo --database=rethinkdb`

**Comment by angeloashmore** [comment]
It looks like Hanami's CLI includes a database option when creating a new app. Please see the CLI file here: https://github.com/hanami/hanami/blob/master/lib/hanami/commands/new/app.rb. I have not used Hanami in some time now, so I am unsure if the database CLI option enables the functionality you are after.

As this is a Hanami-specific question, I will be closing this issue.
